<?php return array (
  'site_web_title' => '小丑路人博客',
  'site_web_author' => '小丑路人',
  'site_web_keywords' => '小丑路人,小丑,路人,小丑疯狂吧,小丑博客,博客,laravel,yii,mysql',
  'site_web_description' => '小丑路人,小丑,路人,小丑疯狂吧,小丑博客,博客,laravel,yii,mysql',
  'site_web_site_icp' => '晋ICP备18007574号-1',
  'site_web_logo' => '/static/blog.jpg',
  'START_API_LOGS' => '1',
  'ARTICLE_CACHE_TIME' => '60',
  'WEB_SITE_CLOSE' => '1',
  'config_group_list' =>
  array (
    0 => '不分组',
    1 => '基本',
    2 => '内容',
    3 => '用户',
    4 => '系统',
    5 => '博主',
    6 => '开发者',
    7 => '网站后台',
    8 => 'JWT',
    9 => '小丑社区配置',
    10 => '数据库',
  ),
  'config_type_list' =>
  array (
    0 => '字符串',
    1 => '文本',
    2 => '数字',
    3 => '数组',
    4 => '枚举',
    5 => '图片',
    6 => '富文本',
  ),
  'web_detault_show_img' => '/static/blog.jpg',
  'web_url' => '',
  'api_admin_prefix' => 'admin',
  'web_admin_title' => '小丑路人博客后台管理',
  'web_admin_keywords' => '小丑路人博客后台',
  'web_admin_description' => '小丑路人博客后台',
  'menu_type_list' =>
  array (
    0 => '作为频道页，不可作为栏目发布文章',
    1 => '不直接发布内容，用于跳转页面',
    2 => '作为发布栏目，文章列表模式',
    3 => '单页面模式，例如企业简介',
  ),
  'admin_prefix' => 'admin',
  'ADMIN_VIEWS' => '/_admin/',
  'privateKey' => '&lt;&lt;&lt;EOD-----BEGIN RSA PRIVATE KEY-----MIICXAIBAAKBgQC8kGa1pSjbSYZVebtTRBLxBz5H4i2p/llLCrEeQhta5kaQu/RnvuER4W8oDH3+3iuIYW4VQAzyqFpwuzjkDI+17t5t0tyazyZ8JXw+KgXTxldMPEL95+qVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4ehde/zUxo6UvS7UrBQIDAQABAoGAb/MXV46XxCFRx',
  'publicKey' => '&lt;&lt;&lt;EOD-----BEGIN PUBLIC KEY-----MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8kGa1pSjbSYZVebtTRBLxBz5H4i2p/llLCrEeQhta5kaQu/RnvuER4W8oDH3+3iuIYW4VQAzyqFpwuzjkDI+17t5t0tyazyZ8JXw+KgXTxldMPEL95+qVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4ehde/zUxo6UvS7UrBQIDAQ',
  'jwt_leeway' => '60',
  'jwt_token_name' => 'cnpscy-token',
  'return_jwt_token_name' => 'jwt_token',
  'server_user_unqiue' => 'login-user-id',
  'start_api_logs' => '1',
  'start_admin_operation_logs' => '1',
  'resource_version_number' => '20200410',
  'admin_default_pass' => '123456',
  'web_cdn_address' => '',
  'cnpscy_version_number' => 'v1.0',
  'system_timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => '',
  'admin_menu_session_unique' => 'rabc_menus_list',
  'admin_info_session_unique' => 'admin_info',
  'admin_rabc_session_unique' => 'admin_rabc',
);
