<?php

namespace App\Modules\Admin\Services;

use App\Models\UploadFile;

class FileService extends BaseService
{
    public function __construct(UploadFile $uploadFile)
    {
        $this->model = $uploadFile;
    }

    public function lists(array $params): array
    {
        $params['where_callback'] = function($query) use ($params){
            $request = request();
            // 按照名称进行搜索
            if (!empty($search = $request->input('search', ''))){
                $query->where('file_name', 'LIKE', '%' . trim($search) . '%');
            }
        };
        $params['order'] = 'file_id';
        $params['order_sort'] = 'DESC';
        return parent::lists($params); // TODO: Change the autogenerated stub
    }
}
